server:
  port: 8080
easycall:
  provider:
    connString: 192.168.40.128:2181
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
    fetch-registry: true
    register-with-eureka: false
spring:
  application:
    name: person-provider